server:
  port: 8080

spring:
  #ÅäÖÃactiveMq ·şÎñÆ÷
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    #ÅäÖÃrabbitMq ·şÎñÆ÷
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #ÅäÖÃredis
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
